### ISSUE TITLE
Default Booking -> Same time frame saved in One Bookings For Many.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#31]
**Description**

Creating a new Default booking product for One Booking for Many type, I have added slot of Time 08:00 to 08:00.  Same time frame is saved. 

**Steps to Reproduce**

1. Go to Admin -> Catalog -> Products -> Create -> Booking -> Select Type Default.
2. Now select booking type -> One Booking for Many.
3. Now add dates and use same for twice.
4. Save the details.
5. Check and found that the details are saved.

**Actual Concern**

Currently we can see that the details are saved and also we can see that double the details related to the same dates are appearing.

Please find the screenshot below.

**Screenshot**

**Admin End**

![Screenshot from 2024-02-22 13-40-52](https://github.com/bagisto/booking-product/assets/92721837/ab9ef78f-2d61-4152-90d7-9acbb97aa5b7)

**Shop Front**

![Screenshot from 2024-02-22 13-40-42](https://github.com/bagisto/booking-product/assets/92721837/33b9139b-1f65-4eff-83a5-635887354ea8)

**Expected Result**

Same Dates should not be saved. Validation should appear.

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, 

This issue is fixed in this [PR](https://github.com/bagisto/booking-product/pull/41).

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue is still appearing after the PR is merged. Please fix the issue again. For reference I am attaching a video and screenshot.

**Video**

https://github.com/bagisto/booking-product/assets/92721837/44ce6bea-6269-4b4f-b9d8-aa5833ffc407

**Screenshot**

![Screenshot from 2024-03-27 12-17-53](https://github.com/bagisto/booking-product/assets/92721837/b051ccee-f59f-49de-a403-528cebbfd698)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that now the duplicate entyr is not saving. Hence the issue is fixed and working fine. Please check the video for reference.

**Video**

https://github.com/bagisto/booking-product/assets/92721837/d921941f-3678-4e52-8fd0-eccdffdad899
